import { Color } from 'expangine-runtime';
import { LiveContext, LiveResult, LiveCommand } from './LiveRuntime';
export declare function saveScope<K extends string>(context: LiveContext, scope: Record<string, K>): Record<K, any>;
export declare function restoreScope<K extends string>(context: LiveContext, saved: Record<K, any>): void;
export declare function preserveScope<R = any>(context: LiveContext, props: string[], run: () => R): R;
export declare function _optional(cmd: LiveCommand | undefined, context: LiveContext, defaultValue?: LiveResult): LiveResult;
export declare function _bool(cmd: LiveCommand | undefined, context: LiveContext, defaultValue?: boolean): boolean;
export declare function _typed<T>(isValid: (value: any) => value is T, invalidValueDefault: T): (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: T) => T;
export declare function _typedDynamic<T>(isValid: (value: any) => value is T, invalidValueDefault: () => T): (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: () => T) => T;
export declare const _boolMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: boolean) => boolean;
export declare const _number: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: number) => number;
export declare const _numberMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: number) => number;
export declare const _text: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: string) => string;
export declare const _textMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: string) => string;
export declare const _list: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: () => any[]) => any[];
export declare const _listMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: any[]) => any[];
export declare const _map: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: () => Map<any, any>) => Map<any, any>;
export declare const _mapMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: Map<any, any>) => Map<any, any>;
export declare const _object: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: () => any) => any;
export declare const _objectMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: any) => any;
export declare const _color: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: () => Color) => Color;
export declare const _colorMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: any) => any;
export declare const _date: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: () => Date) => Date;
export declare const _dateMaybe: (cmd: import("expangine-runtime").Command<LiveContext, any>, context: LiveContext, invalidValue?: Date) => Date;
export declare function _asList(getValue: LiveCommand, context: LiveContext): any[];
export declare function _asMap(getValue: LiveCommand, context: LiveContext): Map<string, any>;
export declare function _asObject(getValue: LiveCommand, context: LiveContext): {
    value: any;
};
export declare function _asTuple(getValue: LiveCommand, context: any): any[];
export declare function _colorOrNumber(getValue: LiveCommand, context: any): Color;
export declare function _regex(getPattern: LiveCommand, context: any, g?: LiveCommand | boolean, i?: LiveCommand | boolean, m?: LiveCommand | boolean): RegExp;
export declare function _regexFlag(flag: LiveCommand | boolean | undefined, context: any, defaultValue?: boolean): boolean;
